package ru.itmo.lab1;

public enum TracePoint {
    INSERT_START,
    ROOT_FULL_SPLIT,
    DESCEND_TO_CHILD,
    INSERT_INTO_LEAF,
    INSERT_INTO_INTERNAL,

    SPLIT_CHILD_START,
    SPLIT_CHILD_PROMOTE_MIDDLE,
    SPLIT_CHILD_DONE,

    SEARCH_START,
    SEARCH_HIT,
    SEARCH_MISS,
    SEARCH_DESCEND
}