#spring.datasource.url=jdbc:postgresql://pg:5432/studs
#spring.datasource.username=s342951
#spring.datasource.password=jRBZRXczxMxm6C7b
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=slkdjqoigjqwokjqwpokdfja123412341234123514694879
jwt.expiration=3600000
server.ssl.enabled=false
logging.level.root=INFO
logging.level.org.springframework=DEBUG
spring.jpa.hibernate.ddl-auto=update