src.dir=src/main/java
test.src.dir=src/test/java

build.dir=build
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes
test.reports.dir=${build.dir}/test-reports

war.dir=dist
war.name=web3
project.version=1.0

lib.dir=lib

target.java.version=17
encoding=UTF-8

music.player=afplay
music.sound=src/main/resources/db/success.mp3